config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :categories
  resources :sections
  resources :cities
  root to: "sections#index"

  get 'sections/show_categories'
  get 'sections/:id/show_categories', to: 'sections#show_categories', as: 'section_show_categories'

  get 'sections/show_posts'
  get 'sections/:id/show_posts', to: 'sections#show_posts', as: 'section_show_posts'
  
  get 'categories/show_posts'
  get 'categories/:id/show_posts', to: 'categories#show_posts', as: 'category_show_posts'
  
  get 'cities/show_posts'
  get 'cities/:id/show_posts', to: 'cities#show_posts', as: 'city_show_posts'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
    has_many :categories
    has_many :posts
    validates  :name, presence:true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy, :show_categories, :show_posts]
  skip_before_action :authenticate_user!, only: [:index]
  skip_before_action :deny_access, only: [:index, :show_categories, :show_posts]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
    # @posts = Post.all
    @cities = City.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  def show_posts
		@posts = @section.posts	
  end

  def show_categories
   render json: @section.categories
  end

  
  def show_sections
		render json: @section.sections	
	end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:name)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_cities.html.erb
<div id="rightbar">
<div class="row">
<div class="col">
<div id="ccc" class="col">
        <h5 class="ban hot active">US Cities</h5>
        <ul class="acitem" style="display: block;">
            <% @cities.each do |city| %>
                <li class="s"><a href="<%= city_show_posts_path(city.id) %>"><%= city.name %></a></li>
            <% end %>
        </ul>
</div>
 </div>
</div>
</div>

app/views/sections/_example.html.erb
<div id="center">
	<% @sections.each do |section| %>  
			<div id="ccc" class="col">
				<h4 class="ban"><a href= "<%= section_show_posts_path(section.id) %>" class="ccc" data-alltitle="all <%= section.name %>" data-cat="ccc"><span class="txt"><%= section.name %><sup class="c"></sup></span></a></h4>
				<div class="cats">
					<ul id="ccc0" class="left">
						<% section.categories.each do |category| %>
							<li><a href="<%= category_show_posts_path(category.id) %>" class="<%= category.name %>" data-cat="<%= category.name %>"><span class="txt"><%= category.name %><sup class="c"></sup></span></a></li>				
						<% end %>
					</ul>
				</div>
			</div>
	<% end %>
</div>

app/views/sections/_form.html.erb
<div class="container">
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div class="field">
  <b>
    <%= form.label :name %>
</b>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/sections/_leftbar.html.erb
<div id="leftbar">
    <a href="/">CRAIGSLIST</a>
<ul id="postlks" class="m-5">
		<% if user_signed_in? %>
  <li class="mb-3"><a href="#">Logged in as <strong><%= current_user.email %></a></strong></li>
  <li class="mb-3"> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
  <li class="mb-3"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
<% else %>
  <li class="mb-3"><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
  <li class="mb-3"><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
<% end %>
</ul>
</div>

<div class="container mb-4">
<button class="btn btn-primary">
 <a id="post" href="<%= new_post_path %> ">create a posting</a>
 </button>
 </div>

app/views/sections/edit.html.erb
<div class="container mt-5">
    <h1 class="text-center">Editing Section</h1>

    <%= render 'form', section: @section %>

    <br>
    <%= link_to 'Show', @section %> |
    <%= link_to 'Back', sections_path %>
<div>

app/views/sections/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
     <%= render 'leftbar' %>
    </div>
    <div class="col-6">
     <%= render 'example' %>
    </div>
    <div class="col">
     <%= render 'cities' %>
    </div>
  </div>
  <br>
</div>

  <div>
<%= link_to 'New Section', new_section_path %>
</div>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path, class: "btn btn-primary" %>

app/views/sections/show.html.erb
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @section.name %>
  </p>

<br>
  <%= link_to 'Edit', edit_section_path(@section) %> |
  <%= link_to 'Back', sections_path %>
<div>

app/views/sections/show_posts.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <h1 class="text-center mt-4">Posts</h1>

  <div class="row mt-4">

    <% @posts.each do |post| %>
        <div class="card-group">
          <div class="card mb-3">
              <div class="card-body">
                <h5 class="card-title">Title: <%= post.title %></h5>
                <h6 class="card-text">Price:  <%= post.price %></h6>
                <h6 class="card-text">Postal code: <%= post.postal_code %></h6>
                <h6 class="card-text">Phone number: <%= post.phone_number %></h6>
                <h6 class="card-text">Description: <%= post.description %></h6>
                <h6 class="card-text">Active: <%= post.active %></h6>

                  <hr>
                  <br>
                     <div class="container">
                  <div class="row justify-content-md-center">
                      <% (0...post.pictures.count).each do |picture| %>
                        <div class="card-image-bottom"style="width:100px; height:100px">
                            <%= image_tag(post.pictures[picture], style: 'width:100% ; height:auto' ) %>
                        </div>
                      <% end %>
                  </div>
                </div>

                <a><%= link_to 'Edit', edit_post_path(post) %></a> |
                <a><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></a>
              </div>
          </div>
        </div>
    <% end %>

    <br>

   
  </div>
   <%= link_to 'New Post', new_post_path, class:"btn btn-primary" %>
</div>