config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :categories
  resources :sections
  resources :cities
  root to: "sections#index"

  get 'sections/show_categories'
  get 'sections/:id/show_categories', to: 'sections#show_categories', as: 'section_show_categories'

  get 'sections/show_posts'
  get 'sections/:id/show_posts', to: 'sections#show_posts', as: 'section_show_posts'
  
  get 'categories/show_posts'
  get 'categories/:id/show_posts', to: 'categories#show_posts', as: 'category_show_posts'
  
  get 'cities/show_posts'
  get 'cities/:id/show_posts', to: 'cities#show_posts', as: 'city_show_posts'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    belongs_to :section
    validates  :name, :section_id, presence:true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :show_posts]
  skip_before_action :deny_access, only: [:show_posts]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    # @posts = Post.all
  end

  def show_posts
    @posts = @category.posts
	end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :section_id)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container mt-5">
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br>
  <div class="field">
  <b>
    <%= form.label :name %>
  </b>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
  <b>
    <%= form.label :section_id %>
  </b>
    <%= select_tag "category[section_id]", options_from_collection_for_select(Section.all, "id", "name", category.section ? category.section.id : ""), class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
<br>
<div>

app/views/categories/edit.html.erb
<div class= "mt-10 container">
    <h1 class="text-center">Editing Category</h1>

    <%= render 'form', category: @category %>

    <%= link_to 'Show', @category %> |
    <%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container mt-5">
<b><h1 class="text-center">Categories</h1></b>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.section.name %></td>
        <td><%= link_to 'Show', category, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class: "btn btn-warning" %>
</div>

app/views/categories/new.html.erb
<div class="container mt-5">
    <h1 class="text-center">New Category</h1>

    <%= render 'form', category: @category %>

    <%= link_to 'Back', categories_path %>
</div >

app/views/categories/show.html.erb
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @category.name %>
  </p>

  <p>
    <strong>Section:</strong>
    <%= @category.section.name %>
  </p>

  <%= link_to 'Edit', edit_category_path(@category) %> |
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show_posts.html.erb
<%= render 'layouts/navbar' %>

<div class="container">
  <h1 class="text-center mt-4">Posts</h1>

  <div class="row mt-4">

    <% @posts.each do |post| %>
        <div class="card-group">
          <div class="card mb-3">
              <div class="card-body">
                <h5 class="card-title">Title: <%= post.title %></h5>
                <h6 class="card-text">Price:  <%= post.price %></h6>
                <h6 class="card-text">Postal code: <%= post.postal_code %></h6>
                <h6 class="card-text">Phone number: <%= post.phone_number %></h6>
                <h6 class="card-text">Description: <%= post.description %></h6>
                <h6 class="card-text">Active: <%= post.active %></h6>

                  <hr>
                  <br>
                 <div class="container">
                  <div class="row justify-content-md-center">
                      <% (0...post.pictures.count).each do |picture| %>
                        <div class="card-image-bottom"style="width:100px; height:100px">
                            <%= image_tag(post.pictures[picture], style: 'width:100% ; height:auto' ) %>
                        </div>
                      <% end %>
                  </div>
                </div>

                <a><%= link_to 'Edit', edit_post_path(post) %></a> |
                <a><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></a>
              </div>
          </div>
        </div>
    <% end %>

    <br>

   
  </div>
   <%= link_to 'New Post', new_post_path, class:"btn btn-primary" %>
</div>